version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  testtask.web-server:
      image: mgsvtts/testtask.web-server:latest
      ports: 
        - "7000:8080"
        - "7010:8081"
      environment:
      - DOTNET_RUNNING_IN_CONTAINER=true

  testtask.grpc-server:
      image: mgsvtts/testtask.grpc-server:latest
      ports: 
        - "7001:8080"
        - "7011:8081"
      environment:
      - DOTNET_RUNNING_IN_CONTAINER=true

  testtask.console:
      image: mgsvtts/testtask.console:latest
      ports: 
        - "7002:8080"
        - "7012:8081"
      stdin_open: true 
      tty: true

volumes:
  redis_data:
